#this is for running in development
version: '3.5'
services:
    backend:
        depends_on:
            - data-container
        image: docker.ub.gu.se/rails:ruby-2.3.1-002
        # test data 
        # data-cointainer holds a set of Mets packages for testing purpose
        volumes_from:
            - data-container:rw
        volumes:
            - ../dliver-server:/usr/src/app
        command: ["sh", "-c", "bundle install && rm -f /usr/src/app/tmp/pids/server.pid && rails server -b 0.0.0.0"]
    frontend:
        image: docker.ub.gu.se/ember-dev:1.13.8
        ports:
            # server
            - 4200:4200
            # livereload
            - 35730:35730
            # Tests in browser
            - 7357:7357
        volumes:
            - ../dliver:/home/node/app
    postgres:
        image: postgres:9.4
        volumes:
            - ./build/postgres/postgres.conf:/etc/postgresql/postgresql.conf
    solr:
        image: solr:5.5.5
        volumes:
            - ./solr_config/dliver:/opt/solr/server/solr/dliver
    data-container:
        image: docker.ub.gu.se/dliver-development-data:001

        
        
            
