version: '3.5'
services:
    backend:
        restart: always
        environment:
            - ENVIRONMENT=${ENVIRONMENT}
            - DB_HOST=${DB_HOST}
            - DB_PORT=5432
            - DB=${DB}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - SECRET_KEY_BASE=${SECRET_KEY_BASE}
            - AUTH_URL=${AUTH_URL}
            - SOLR_URL=${SOLR_URL}
            - CACHE_PATH=${CACHE_PATH}
            - STORE_PATH=${STORE_PATH}
            - DEFAULT_THUMBNAIL=${DEFAULT_THUMBNAIL}
            - THUMBNAIL_FILE_GROUP=${THUMBNAIL_FILE_GROUP}
        ports:
            - ${RAILS_SERVICE_PORT}:3000

    frontend:
        # Keep the stdin open, so we can attach to our app container's process
        # and do things such as debugging, etc
        stdin_open: true
        tty: true
        environment:
            - EMBER_ENVIRONMENT=${ENVIRONMENT}
            - BACKEND_URL=${BACKEND_URL}
            - BACKEND_SERVICE_PORT=${RAILS_SERVICE_PORT}
    db:
        image: postgres:9.4
        restart: always
        environment:
            - POSTGRES_DB=${DB}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./build/postgres/postgres.conf:/etc/postgresql/postgresql.conf
            - ./postgres-initdb.d:/docker-entrypoint-initdb.d
            - dbdata:/var/lib/postgresql/data
    solr:
        image: dliver-solr:002
        restart: always
volumes:
    dbdata: